
export const MOCK_COURSES = [
    {
        id: "course-1",
        title: "Complete Web Development Bootcamp",
        description: "Learn web development from scratch with this comprehensive course covering HTML, CSS, JavaScript, React, and more.",
        thumbnail_url: "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "John Doe",
        instructor_avatar: null,
        tags: ["Web Dev", "React", "JavaScript"],
        difficulty: "beginner",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 120, modules: 10, lessons: 45 }
    },
    {
        id: "course-2",
        title: "Advanced React Patterns",
        description: "Master advanced React patterns and best practices for building scalable applications.",
        thumbnail_url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Jane Smith",
        instructor_avatar: null,
        tags: ["React", "Advanced"],
        difficulty: "advanced",
        is_published: true,
        is_featured: false,
        created_by: "admin",
        created_at: new Date(Date.now() - 86400000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 85, modules: 8, lessons: 32 }
    },
    {
        id: "course-3",
        title: "UI/UX Design Fundamentals",
        description: "Learn the principles of beautiful and functional user interface design.",
        thumbnail_url: "https://images.unsplash.com/photo-1586717791821-3f44a5638d48?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Sarah Lee",
        instructor_avatar: null,
        tags: ["Design", "Figma", "UI/UX"],
        difficulty: "beginner",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date(Date.now() - 172800000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 200, modules: 12, lessons: 50 }
    },
    {
        id: "course-4",
        title: "Python for Data Science & Machine Learning",
        description: "Master Python programming for data analysis, visualization, and machine learning with hands-on projects using Pandas, NumPy, and Scikit-Learn.",
        thumbnail_url: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Dr. Alex Rivera",
        instructor_avatar: null,
        tags: ["Python", "Data Science", "ML"],
        difficulty: "intermediate",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date(Date.now() - 259200000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 340, modules: 14, lessons: 68 }
    },
    {
        id: "course-5",
        title: "Cloud Architecture with AWS",
        description: "Design and deploy scalable cloud solutions using Amazon Web Services. Covers EC2, S3, Lambda, DynamoDB, and more.",
        thumbnail_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Michael Chen",
        instructor_avatar: null,
        tags: ["AWS", "Cloud", "DevOps"],
        difficulty: "intermediate",
        is_published: true,
        is_featured: false,
        created_by: "admin",
        created_at: new Date(Date.now() - 345600000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 156, modules: 9, lessons: 38 }
    },
    {
        id: "course-6",
        title: "Mobile App Development with Flutter",
        description: "Build stunning cross-platform mobile apps with Flutter and Dart. Create beautiful, natively compiled applications for iOS and Android.",
        thumbnail_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Priya Sharma",
        instructor_avatar: null,
        tags: ["Flutter", "Dart", "Mobile"],
        difficulty: "beginner",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date(Date.now() - 432000000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 278, modules: 11, lessons: 52 }
    },
    {
        id: "course-7",
        title: "Cybersecurity Essentials",
        description: "Learn the fundamentals of cybersecurity including threat analysis, ethical hacking, network security, and incident response.",
        thumbnail_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "James Wilson",
        instructor_avatar: null,
        tags: ["Security", "Hacking", "Networks"],
        difficulty: "intermediate",
        is_published: true,
        is_featured: false,
        created_by: "admin",
        created_at: new Date(Date.now() - 518400000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 192, modules: 10, lessons: 42 }
    },
    {
        id: "course-8",
        title: "Modern JavaScript: ES6 to ESNext",
        description: "Deep dive into modern JavaScript features — from ES6 arrow functions to optional chaining, async generators, and beyond.",
        thumbnail_url: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Emily Carter",
        instructor_avatar: null,
        tags: ["JavaScript", "ES6", "Frontend"],
        difficulty: "beginner",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date(Date.now() - 604800000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 412, modules: 7, lessons: 35 }
    },
    {
        id: "course-9",
        title: "Blockchain & Web3 Development",
        description: "Build decentralized applications with Solidity, Ethereum, and Web3.js. Understand smart contracts, DeFi, and NFT development.",
        thumbnail_url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "David Kim",
        instructor_avatar: null,
        tags: ["Blockchain", "Web3", "Solidity"],
        difficulty: "advanced",
        is_published: true,
        is_featured: false,
        created_by: "admin",
        created_at: new Date(Date.now() - 691200000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 98, modules: 8, lessons: 30 }
    },
    {
        id: "course-10",
        title: "Next.js Full-Stack Masterclass",
        description: "Build production-ready full-stack applications with Next.js 14, Server Actions, App Router, and modern deployment strategies.",
        thumbnail_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Rachel Green",
        instructor_avatar: null,
        tags: ["Next.js", "Full-Stack", "React"],
        difficulty: "intermediate",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date(Date.now() - 777600000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 265, modules: 13, lessons: 55 }
    },
    {
        id: "course-11",
        title: "Docker & Kubernetes for Developers",
        description: "Master containerization with Docker and orchestrate microservices with Kubernetes. Deploy, scale, and manage applications like a pro.",
        thumbnail_url: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Omar Hassan",
        instructor_avatar: null,
        tags: ["Docker", "Kubernetes", "DevOps"],
        difficulty: "advanced",
        is_published: true,
        is_featured: false,
        created_by: "admin",
        created_at: new Date(Date.now() - 864000000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 134, modules: 9, lessons: 40 }
    },
    {
        id: "course-12",
        title: "Graphic Design with Adobe Creative Suite",
        description: "Create stunning visual designs using Photoshop, Illustrator, and InDesign. From branding to social media — become a design pro.",
        thumbnail_url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=2070&auto=format&fit=crop",
        instructor_name: "Lisa Park",
        instructor_avatar: null,
        tags: ["Photoshop", "Illustrator", "Design"],
        difficulty: "beginner",
        is_published: true,
        is_featured: true,
        created_by: "admin",
        created_at: new Date(Date.now() - 950400000).toISOString(),
        updated_at: new Date().toISOString(),
        _count: { enrollments: 310, modules: 15, lessons: 60 }
    },
];

export const MOCK_MODULES = [
    {
        id: "mod-1",
        course_id: "course-1",
        title: "Introduction",
        description: "Getting started with the course",
        order_index: 0,
        created_at: new Date().toISOString(),
        lessons: [
            {
                id: "les-1",
                module_id: "mod-1",
                course_id: "course-1",
                title: "Welcome to the Course",
                description: "Overview of what we will learn",
                video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                video_type: "youtube",
                duration_seconds: 120,
                order_index: 0,
                created_at: new Date().toISOString(),
                notes: "Welcome!",
                resources: [],
                completed: false
            }
        ]
    }
];
